#Esto es el dockerfile para desarrollo 

FROM maven:3.9-openjdk-17-slim
WORKDIR /app
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copia la configuración Maven
COPY pom.xml .
COPY .mvn/ .mvn/
RUN mvn dependency:go-offline -B
# Copia el código fuente
COPY src ./src
EXPOSE 8080 5005
ENV SPRING_PROFILES_ACTIVE=dev
ENV JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
